Re-skeletonize
cisagov/ansible-role-cyhy-logrotate pull request #9
Opened 2022-05-17 21:13 UTC by jsf9k

## 🗣 Description ##

This pull request re-skeletonizes this repository.

## 💭 Motivation and context ##

This repository needs to be re-skeletonized since it was based on an ancient skeleton that lacked even a Lineage configuration.

## 🧪 Testing ##

Automated testing passes.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

2022-05-18 14:48 UTC, dav3r approved these changes
Looks great, thanks for modernizing this one! 💎

2022-05-19 02:48 UTC, mcdonnnj requested changes
Thanks for helping drag another repo back into the light. I have a question and a suggestion for your consideration. I also wanted to bring up that the dependency [cisagov/ansible-role-logrotate](https://github.com/cisagov/ansible-role-logrotate) needs to be updated the same way as this repo.

2022-05-19 02:48 UTC, mcdonnnj commented on molecule/default/prepare.yml
>      - name: Temporary workaround for ansible/ansible#56583
Do we still need this now that the linked issue is closed? Per https://github.com/cisagov/ansible-role-banner/commit/3cddad3734b6924d0713b81b4a56c557abf70e35 it was resolved and subsequently removed from that repository.

2022-05-19 02:48 UTC, mcdonnnj commented on molecule/default/requirements.yml
>  - src: https://github.com/dhs-ncats/ansible-role-logrotate
```suggestion
- src: https://github.com/cisagov/ansible-role-logrotate
```

2022-05-19 03:33 UTC, jsf9k commented on molecule/default/prepare.yml
>      - name: Temporary workaround for ansible/ansible#56583
Good point.  I meant to follow up on that but forgot.  Please see commit 15e759d.

2022-05-19 15:14 UTC, mcdonnnj approved these changes
:shipit:

2022-05-20 15:33 UTC, jsf9k commented
> I also wanted to bring up that the dependency [cisagov/ansible-role-logrotate](https://github.com/cisagov/ansible-role-logrotate) needs to be updated the same way as this repo.

@mcdonnnj - Please see cisagov/ansible-role-logrotate#8.

2022-05-23 19:39 UTC, merged